site_name: "Kane vs Abel Arena"
nav:
  - Home: arena.md
  - Environment: 
    - Action Space: action_space.md
    - Additional Games: adding_diff_game.md
  - Agents:
    - Behaviour Tree: behaviour_tree.md
    - Human Input: human_input.md
    - DQN: dqn.md
  - RL Training:
    - Overview: model_training.md
    - Curriculum Learning: curriculum_learning.md
    - Model Evaluation: model_evaluation.md
    - Fine-tuning Models: model_finetuning.md
  
theme:
  name: readthedocs
  palette:
    scheme: slate  
    toggle:
      icon: material/weather-night
      name: Switch to light mode
use_directory_urls: false
extra:
  homepage: arena.md